const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');
const creds = require('./configs/cot-storyteller-6781c6d9e0e6.json');

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: creds.client_email,
  key: creds.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

const notableOffspringDoc = new GoogleSpreadsheet('1aeV5rxNkqA-5qR4971XU2HykvSAa5gfLGK8qt5uZjWA', serviceAccountAuth);
const citizenryRegistryDoc = new GoogleSpreadsheet('1lgMUEWK4_4OWb1sIzLeds1F3qIFpfZvH4t9Y32cJze4', serviceAccountAuth);

module.exports = { notableOffspringDoc, citizenryRegistryDoc }