const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');

let creds;
try {
  creds = require('./configs/googleserviceaccount.json');
}
catch (error) {
  if (error.code === 'MODULE_NOT_FOUND') {
    console.log('Google service account credentials not found in configs/googleserviceaccount.json. Spreadsheets will not be synced to the database.');
    module.exports = { citizensDoc: null, offspringDoc: null };
    return;
  } else {
    throw error;
  }
}

let citizensSpreadsheetId, offspringSpreadsheetId;
try {
  const spreadsheetsConfig = require('./configs/spreadsheets.json');
  citizensSpreadsheetId = spreadsheetsConfig.citizensSpreadsheetId;
  offspringSpreadsheetId = spreadsheetsConfig.offspringSpreadsheetId;
} catch (error) {
  if (error.code === 'MODULE_NOT_FOUND') {
    console.log('Spreadsheet configuration not found in configs/spreadsheets.json. Spreadsheets will not be synced to the database.');
    module.exports = { citizensDoc: null, offspringDoc: null };
    return;
  } else {
    throw error;
  }
}

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: creds.client_email,
  key: creds.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

// Initialize the GoogleSpreadsheet objects for both spreadsheets
const citizensDoc = new GoogleSpreadsheet(citizensSpreadsheetId, serviceAccountAuth);
const offspringDoc = new GoogleSpreadsheet(offspringSpreadsheetId, serviceAccountAuth);

module.exports = { citizensDoc, offspringDoc }